apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-yvtu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xybp-tenant/rhtap-demo-app/hacbs-test-project-yvtu@sha256:6276fba2ef738267cd58ee13fdf4f7e9dde807751597e6fcb5d5e7145907c015
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
