apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-yvtu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xybp-tenant/rhtap-demo-app/hacbs-test-project-yvtu@sha256:574803b06e9c844ae4eea7ec20a1a1a68d170a8beda609a0854f0fb602762ec6
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
