apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-yvtu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-yvtu
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-yvtu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-yvtu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-yvtu
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xybp-tenant/rhtap-demo-app/hacbs-test-project-yvtu@sha256:574803b06e9c844ae4eea7ec20a1a1a68d170a8beda609a0854f0fb602762ec6
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
